### ISSUE TITLE
Feature Suggestion: Multi-tenant RDS PostgreSQL database

### ISSUE THREAD

**Issue by darpham** [hackforla/incubator#1]
### Overview
Need to implement way to dynamically add database resources within the Multi-tenant/Incubator Database.
This will require creating:
- Database/Tables
- User
- Roles
- Permission restrictions

**Comment by nyarly** [comment]
This is important for Access the Data. Let's look into using e.g. https://registry.terraform.io/providers/SpencerBinXia/postgresql/latest/docs for this
