### ISSUE TITLE
Deploy Civic Tech Jobs on staging

### ISSUE THREAD

**Issue by JasonEb** [hackforla/incubator#13]
### Overview
The Civic Tech Jobs team seeks to deploy their app within HackForLA's AWS incubator account. The Ops team can deploy their docker build. 

- [x] What environment should it be?

### Action Items
- [x] Setup project.hcls
- [x] Apply Terragrunt to provision AWS
- [x] Push Docker-build onto provisioned Fargate
- [ ] Setup github action to deploy back-end/front-end builds to production environment

### Resources/Instructions
[Incubator](https://drive.google.com/drive/folders/1_UZtr0P-GYR8aQbNiEGwS5_vdDccooSG)
[CivicTechJobs Repo](https://github.com/hackforla/CivicTechJobs)

**Comment by JasonEb** [comment]
What environments shall it be deployed on?

**Comment by JasonEb** [comment]
9/7 Update

Ava has shared ops a project.hcl for CTJ's staging. 

I ran the project.hcl file through `terragrunt` and debugged parsing issues. For the `container_env_vars` in project.hcl, we have to surround the values in strings (for content like URLs and passwords) and numbers.

This highlights some potential issues ops needs to clear up.
```json
container_env_vars = {
    ..
    DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    SQL_ENGINE=django.db.backends.postgresql
}
```

For `DJANGO_ALLOWED_HOSTS`, the value "localhost 127.0.0.1 [::1]" implies 3 values for input. I tried using ["localhost", "127.0.0.1", "[::1]"] but Terragrunt reported that these values need to be String. For now I set it to `DJANGO_ALLOWED_HOSTS="localhost"`

For `SQL_ENGINE`, I set the key to `"django.db.backends.postgresql"`.  However the original value implies the configuration to read a `django` object for its backend. Not sure what that's suppose to return. Can we hardcode that? How do we setup django in this context?  Or is this string sufficient for CTJ's needs?

**Comment by JasonEb** [comment]
@Aveline-art we have provisioned resources

![image](https://user-images.githubusercontent.com/6300995/189550077-894aa723-8a5a-4241-8e5b-b8e262856ae5.png)

![image](https://user-images.githubusercontent.com/6300995/189550092-8db23f04-c2ac-4eda-bdbd-68c41c505f15.png)

I'll reach out to you in the coming week to share the push commands to send the docker image from your end.

**Comment by JasonEb** [comment]
CivicTechJobs staging deployment update

Progress: 
CivicTechJobs has been provisioned on AWS and has a repo ready. Last authenticated Kevin P to push docker images. 

Next step is to attempt to push docker images with the commands shared.

**Comment by gjagnoor** [comment]
CivicTechJobs staging deployment update

Progress:
Kevin P is now able to push docker images from aws-cli and through github actions. 

Next step is to use these docker images in the deployment using ECS and Fargate

**Comment by JasonEb** [comment]
Seems like we hit a good checkpoint for a status update. Last I recall, KevinP had setup db credentials utilizing lamba code from the incubator. Are there any issues for domain names?

The next thing I want to focus on is setting up github action workflow for triggering builds. 

Please provide update, whenever good:
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.
