### ISSUE TITLE
Create Terraform Plan GitHub action

### ISSUE THREAD

**Issue by Tyson-miller** [hackforla/incubator#31]
### Overview
When we make changes to terraform modules it would be helpful to see the terraform plan as part of the PR so that people can confirm that the resources that would be created/modified/destroyed make sense. 

### Action Items
- [x] make a AWS user with the necessary permissions to be able to terraform plan and create credentials (key, secret)
- [x] Put those credentials into the incubator GitHub secrets
- [ ] Create a GitHub action to run on all PRs to plan the terraform for directories within `terraform-incubator`  that have been modified.

### Resources/Instructions
https://github.com/marketplace/actions/terraform-plan - marketplace action for terraform plan
https://github.com/marketplace/actions/changed-files - marketplace action for files changed

**Comment by Tyson-miller** [comment]
There is already a user in AWS called `github-action-incubator` with the secrets stored in the repo and the permissions to run terraform plan so step 1 and 2 should both be done

**Comment by Tyson-miller** [comment]
A potentially tricky feature to implement will be detecting which terraform modules actually changed and running the terraform plan for each module that changed. For example, if someone makes changes to `people-depot/dev`, `vrms-backend/dev`, `vrms-backend/live` in one PR then the action should run the terraform plan for all of those directories.

**Comment by chelseybeck** [comment]
Closed w/ this pr: https://github.com/hackforla/incubator/pull/30
