### ISSUE TITLE
Create screenshots of directory and subdirectories in AWS

### ISSUE THREAD

**Issue by robinglov** [hackforla/incubator#34]
### Overview
We need screenshots of directories and subdirectories of all HfLA projects so that we can start to identify what needs to change and or get replaced by new assets.

### Details
Currently, it is difficult to determine which file destination should be in the state file because they are obscured by Terragrunt naming conventions and there are seemly duplicate folder structures.

### Action Items
- [ ] Log in with credentials
- [ ] Add comments with screenshots to this issue

**Comment by chelseybeck** [comment]
it may be easier to visualize this way vs screenshots:

- 📁 terragrunt-states
  - 📁 incubator
    - 📁 access-the-data
      - 📁 dev
        - 📄 terraform.tfstate 
    - 📁 acm
      - 📄 terraform.tfstate 
    - 📁 alb
      - 📄 terraform.tfstate 
    - 📁 ballotnav-api
      - 📄 terraform.tfstate 
    - 📁 ballotnav-graphql
      - 📄 terraform.tfstate 
    - 📁 ballotnav
      - 📄 terraform.tfstate 
    - 📁 bastion
      - 📄 terraform.tfstate 
    - 📁 cicd
      - 📄 terraform.tfstate 
    - 📁 ecs
      - 📄 terraform.tfstate 
    - 📁 multi-db-lambda
      - 📄 terraform.tfstate 
    - 📁 network
      - 📄 terraform.tfstate 
    - 📁 projects-dev
      - 📁 access-the-data
        - 📄 terraform.tfstate
      - 📁 ballotnav-api
        - 📄 terraform.tfstate
      - 📁 civictechindex-api
        - 📄 terraform.tfstate
      - 📁 people-depot-backend
        - 📄 terraform.tfstate
      - 📁 vrms-backend
        - 📄 terraform.tfstate
      - 📁 vrms-client
        - 📄 terraform.tfstate
    - 📁 projects-prod
      - 📁 ballotnav-api
        - 📄 terraform.tfstate
      - 📁 civictechindex-api
        - 📄 terraform.tfstate
      - 📁 home-unit-us-api
        - 📄 terraform.tfstate
      - 📁 home-united-us-api
        - 📄 terraform.tfstate
      - 📁 vrms-backend
        - 📄 terraform.tfstate
      - 📁 vrms-client
        - 📄 terraform.tfstate
    - 📁 projects-stage
      - 📁 civictechindex-api
        - 📄 terraform.tfstate
      - 📁 civictechjobs-copy
        - 📄 terraform.tfstate
      - 📁 civictechjobs-stage
        - 📄 terraform.tfstate
      - 📁 civictechjobs
        - 📄 terraform.tfstate
    - 📁 r53
      - 📄 terraform.tfstate 
    - 📁 rds
      - 📄 terraform.tfstate 
    - 📁 vault
      - 📄 terraform.tfstate 
    - 📄 terraform.tfstate

**Comment by robinglov** [comment]
Screenshots are no longer necessary. Directory listed above.
