### ISSUE TITLE
Create Basic Web Server app for Incubator

### ISSUE THREAD

**Issue by JasonEb** [hackforla/incubator#37]
### Overview
As an Ops Developer, I'd like there to be a basic demonstration of deploying a web application so I can understand and practice deploying on the Incubator platform.

The Incubator is a terraform project that provisions aws resources to deploy web applications. A basic  webserver application that returns a string would be a good project to use as a platform for testing and practicing deployments with Incubator. 

Let's create a basic Express.js or Flask web server, dockerize it, and add it to the Incubator. 

### Action Items
- [ ] Create basic web app
- [ ] Dockerize the web app
  - [ ] https://nodejs.org/en/docs/guides/nodejs-docker-webapp 
- [ ] Setup `project.hcl`
  - [ ] https://github.com/hackforla/incubator/wiki/Incubator-usage#configure-projecthcl 
- [ ] Deploy to Incubator
  - [ ] https://github.com/hackforla/incubator/wiki/Incubator-usage 
- [ ] Document the experience 
  - [ ] https://github.com/hackforla/ops/wiki 

### Resources/Instructions
https://expressjs.com/en/starter/hello-world.html

https://pythonbasics.org/flask-tutorial-hello-world/

https://nodejs.org/en/docs/guides/nodejs-docker-webapp

https://github.com/hackforla/incubator/wiki/Incubator-usage

**Comment by ExperimentsInHonesty** [comment]
https://www.docker.com/blog/how-to-use-the-official-nginx-docker-image/

**Comment by robinglov** [comment]
We are closing this issue
