### ISSUE TITLE
Create Branch rules so that only Merge team members can merge PRs on the incubator app

### ISSUE THREAD

**Issue by robinglov** [hackforla/incubator#48]
### Overview
We need branch protections on all branches in this repo.

### Action Items
- [x] Create a merge team
- [x] [Settings to configure](https://github.com/github/docs/blob/main/content/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches.md#about-branch-protection-settings)
   -  [x] Require pull requests before merging
   - [x] Research the minimum permissions that a level one user needs to have on the code repos (incubator and devops security) so that when a user opens or updates a PR it kicks off the GitHub Action
     -  [x] Restrict who can push to matching branches based on those permissions
   - [x] Search for and select the 'merge team' as entity that will have permission to push to a branch or create a matching branch.

### Resources/Instructions
[About branch protection rules](https://github.com/github/docs/blob/main/content/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches.md)
[Creating branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule#creating-a-branch-protection-rule)
[Managing branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule)

 create a rule for all current and future branches in your repository with the wildcard syntax *

**Comment by chelseybeck** [comment]
@robinglov we should further refine this b/c there aren't protections on the main branch at all. Let's add all branch protections at once.

**Comment by chelseybeck** [comment]
What's the minimum permissions that a level one user needs to have on the code repo so that when a user opens or updates a PR it kicks off the GitHub Action?

Once the branch protections were in place, members were unable to trigger the GHA. We need to research how to enable protections where only the merge team can merge while also granting permissions for our team members to kick off the action

**Comment by ExperimentsInHonesty** [comment]
@chelseybeck does this need further refinement, or is this issue ready for the prioritized backlog?
