### ISSUE TITLE
Determine project.hcl workflow and setup

### ISSUE THREAD

**Issue by JasonEb** [hackforla/incubator#55]
### Overview
As a Dev Ops Engineer, I'd like to know how should I view and manage `project.hcl` files for Incubator. 

Project.hcl file is a configuration file for deploying onto aws with the Incubator's commands. Currently, every team has to manage their project.hcl files on their own 1password vault. We'd like to revisit and review this workflow over questions such as

1.) Who should actively maintain project.hcl files?
  note: we are going to migrate them
2.) Should we keep project.hcl files per team and/or keep a project.hcl files in the Ops vault?
  note: see above/ migrating over to Terraform
3.) What should be the intended workflow around project.hcl file when initiating an Incubator deployment?
  

### Action Items
- [x] Setup meeting between deployment stakeholders
- [ ] Capture workflow into project.hcl documentation

**Comment by chelseybeck** [comment]
We no longer need these as a part of the Terraform configuration
