### ISSUE TITLE
Document the Terraform Modules using Terraform Docs

### ISSUE THREAD

**Issue by chelseyklein** [hackforla/incubator#59]
### Overview
One of the benefits of infrastructure as code (IaC) is that it is self-documenting. Terraform Docs facilitates easy documentation of resources. Install Terraform Docs and create corresponding files for modules inside of terraform-modules. 

### Action Items
- [ ] Read over the Terraform Docs documentation to understand how the templates are used to generate README.md files
- [x] [Install](https://terraform-docs.io/user-guide/installation/) Terraform Docs on your local machine 
- [x] Create .terraform.docs.yml files for each of the modules in terraform-modules.
  - [x] acm
  - [x] applicationlb
  - [x] bastion
  - [x] cheap-secrets
  - [x] cicd_integration
  - [x] database
  - [x] ecr
  - [x] ecs-task
  - [x] ecs
  - [x] multi-container-service
  - [x] multi-tenant-database
  - [x] network
  - [x] private-dns
  - [x] project-zone
  - [x] r53
  - [x] rds
  - [x] redis
  - [x] service
- [x] Create README.md files for each of the projects in terraform-incubator by changing into the project directory where the terraform files are located and running this command `terraform-docs -c .terraform.docs.yml .`
  - [x] acm
  - [x] applicationlb
  - [x] bastion
  - [x] cheap-secrets
  - [x] cicd_integration
  - [x] database
  - [x] ecr
  - [x] ecs-task
  - [x] ecs
  - [x] multi-container-service
  - [x] multi-tenant-database
  - [x] network
  - [x] private-dns
  - [x] project-zone
  - [x] r53
  - [x] rds
  - [x] redis
  - [x] service

### Resources/Instructions
Terraform Docs [documentation](https://terraform-docs.io/user-guide/introduction/)
[Here](https://github.com/hackforla/devops-security/tree/main/terraform/modules/aws-groups) is an example of Terraform Docs in practice. Note how clear it is now which resources this module creates.

**Comment by chelseybeck** [comment]
This issue can (and maybe should?) be split between two people

**Comment by robinglov** [comment]
Does having one issue for the README.md and one for the .terraform.docs.yml make sense as a split?
