### ISSUE TITLE
Deploy VRMS v0.3 on production

### ISSUE THREAD

**Issue by JasonEb** [hackforla/incubator#7]
### Overview
The VRMS team seeks to deploy `v0.3` of their software onto production within HackForLA's AWS incubator account. The Ops team can deploy their docker build. 

### Action Items
- [x] Setup production environment project configurations
- [x] Apply Terragrunt to provision AWS
- [x] Push Docker-build onto provisioned Fargate
- [x] Setup github action to deploy back-end/front-end builds to production environment

### Resources/Instructions
[Incubator](https://drive.google.com/drive/folders/1_UZtr0P-GYR8aQbNiEGwS5_vdDccooSG)
[VRMS Repo](https://github.com/hackforla/VRMS)

**Comment by JasonEb** [comment]
Questions:
1.) Is vrms on production mean deploying both back-end and client?
2.) Are database migrations already considered in the docker?
3.) What url names are we using?
4.) Need to review `project.hcl` values
  - What domain names would production use:
    - CLIENT_URL="https.vrms.io/"?
    - DATABASE_URL= the same server? 
    -  SLACK?
    - GMAIL?
    - MAILHOG?
    - health_check_paths

**Comment by chukalicious** [comment]
.

**Comment by JasonEb** [comment]
VRMS has successfully deployed on prod environments within incubator 6/29/2022
