### ISSUE TITLE
Create Adding and Managing IAM Permissions to Users to Wiki

### ISSUE THREAD

**Issue by JasonEb** [hackforla/incubator#79]
### Overview
As an Ops member, I'd like to have documentation that shows how to apply permissions and manage user groups within AWS IAM so I can have an online reference. 

Documentation should feature screenshots like seen in the Ops Wiki. 

### Action Items
- [ ] Clarify process between Adding Permissions and Adding to User Groups
- [ ] Update wiki
  - [x] Should go under `AWS User Management` 
  - [x] Should have it's heading like "Adding Permissions"  
  - [ ] Should cover and provide an explanation of what an AWS Managed Policy vs Inline
  - [ ] Should have a remark about when to
     - [x]  add a user to a user group
     - [ ] when to add permissions directly to a usergroup or create a new user group for a certain permissions

### Resources/Instructions
https://github.com/hackforla/ops/wiki/AWS-User-Management

https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction_access-management.html

**Comment by chelseybeck** [comment]
Everything in this issue has been resolved. The https://github.com/hackforla/ops/wiki/AWS-User-Management has been deleted.
